# -*-python-*-

Import( "env" )

import os.path
pj = os.path.join

py_dir = pj(os.path.pardir,'openalea','lpy')

# Build wrappers as shared libraries
lib_env=env.Clone()
lib_env.EnableQt4Modules( [ 'QtCore', 'QtGui', 'QtOpenGL', 'QtNetwork',])# 'QtSql', 'QtXml'])
lib_env.AppendUnique( CPPPATH = ['$QT4_CPPPATH/Qt'] )


sources= lib_env.ALEAGlob( '*.cpp' )
target= "__lpy_kernel__"

lib_env.AppendUnique(LIBS= ['lpy','pgltool','pglmath','pglsg','pglalgo','pglgui'])
lib_env.ALEAWrapper( py_dir, target, sources )

