#{% set version = "2.7.2" %}
{% set data = load_setup_py_data() %}

package:
  name: openalea.lpy
  version: {{ data.get('version') }}

source:
  path: ..

about:
  home: https://github.com/openalea/lpy
  license: Cecill-C
  summary: L-Py is a simulation software that mixes L-systems construction with the Python high-level modeling language.

build:
  preserve_egg_dir: True
  number: 1
requirements:
  host:
    - python x.x
    - setuptools
    - openalea.plantgl >=3.17
    - boost x.x
    - pyqt
  build:
    - binutils_impl_linux-64           # [linux]
    - {{ compiler('cxx') }}
    - python x.x
    - cmake 
    - pkg-config                        # [linux]
    - make                              # [unix]
    - menuinst                          # [win]
  run:
    - python x.x
    - setuptools
    - {{ pin_compatible('openalea.plantgl', max_pin='x.x') }} 
    - boost x.x
    - pyqt
    - ipython
    - qtconsole
    - jupyter_client # <6
    - pyopengl
    - pyqglviewer >=1.3
    - jsonschema

app:
  entry: lpy
  summary: Plant simulation software
  icon: icon_64x64.png

test:
  requires:
    - nose
    - pandas
  imports:
    - openalea.lpy
  source_files:
    - test/
    - share/
  commands:
    - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py [unix]
    - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py -I test_axialtree.py -I test_successor_at_scale.py [win]
