{% set data = load_setup_py_data() %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}

package:
  name: openalea.plantgl
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  string: py{{ PY_VER }}
  number: 0
  preserve_egg_dir: True

requirements:
  host:
    - python x.x
    - setuptools
    - setuptools_scm
    - openalea.plantgl >=3.17
    - boost
    - pyqt
  build:
    - binutils_impl_linux-64           # [linux]
    - {{ compiler('cxx') }}
    - python x.x
    - cmake
    - pkg-config                        # [linux]
    - make                              # [unix]
    - menuinst                          # [win]
  run:
    - python x.x
    - setuptools
    - {{ pin_compatible('openalea.plantgl', max_pin='x.x') }}
    - boost
    - pyqt
    - ipython
    - qtconsole
    - jupyter_client # <6
    - pyopengl
    - pyqglviewer >=1.3
    - jsonschema

app:
  entry: lpy
  summary: Plant simulation software
  icon: icon_64x64.png

test:
  requires:
    - pytest
    - pandas
  imports:
    - openalea.lpy
  source_files:
    - test/
    - share/
#  commands:
#    - pytest -v test_predecessor_at_scale.py test_ui.py test_pickle.py [unix]
#    - pytest -v test_predecessor_at_scale.py test_ui.py test_axialtree.py test_successor_at_scale.py test_pickle.py [win]
