# -*-python-*-
Import( "env" )
lib_env= env.Clone()
qt_version = int(lib_env['QT_VERSION'])
if qt_version == 4:
    lib_env.EnableQtModules( [ 'QtCore'])# 'QtSql', 'QtXml'])
else:
    lib_env.EnableQtModules( [ 'QtCore', 'QtConcurrent'])# 'QtSql', 'QtXml'])

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('LPY_MAKEDLL')

lib_env.AppendUnique(LIBS= ['pgltool','pglmath','pglsg','pglalgo','pglgui'])

inc= lib_env.ALEAIncludes( "lpy", includes )

lib = lib_env.ALEALibrary( "lpy",
                           sources, 
                           CPPDEFINES = DEFINES )
