# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\fred\mes documents\develop\vplants\trunk\lpy\src\openalea\lpy\gui\lpymainwindow.ui'
#
# Created: Fri Jul 02 15:54:23 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 622)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scalarDock = QtGui.QDockWidget(self.centralwidget)
        self.scalarDock.setObjectName("scalarDock")
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_8)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scalarEditor = ScalarEditor(self.dockWidgetContents_8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.scalarEditor.setPalette(palette)
        self.scalarEditor.setAlternatingRowColors(True)
        self.scalarEditor.setItemsExpandable(False)
        self.scalarEditor.setAllColumnsShowFocus(True)
        self.scalarEditor.setObjectName("scalarEditor")
        self.gridLayout_2.addWidget(self.scalarEditor, 0, 0, 1, 1)
        self.scalarDock.setWidget(self.dockWidgetContents_8)
        self.gridLayout_3.addWidget(self.scalarDock, 0, 0, 1, 1)
        self.materialDock = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialDock.sizePolicy().hasHeightForWidth())
        self.materialDock.setSizePolicy(sizePolicy)
        self.materialDock.setObjectName("materialDock")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.materialed = MaterialEditor(self.dockWidgetContents_2)
        self.materialed.setObjectName("materialed")
        self.verticalLayout_3.addWidget(self.materialed)
        self.materialDock.setWidget(self.dockWidgetContents_2)
        self.gridLayout_3.addWidget(self.materialDock, 0, 1, 1, 1)
        self.parametersDock = QtGui.QDockWidget(self.centralwidget)
        self.parametersDock.setObjectName("parametersDock")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(9)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.animtimestep = QtGui.QSlider(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animtimestep.sizePolicy().hasHeightForWidth())
        self.animtimestep.setSizePolicy(sizePolicy)
        self.animtimestep.setMinimum(1)
        self.animtimestep.setMaximum(2000)
        self.animtimestep.setProperty("value", 50)
        self.animtimestep.setOrientation(QtCore.Qt.Horizontal)
        self.animtimestep.setObjectName("animtimestep")
        self.hboxlayout.addWidget(self.animtimestep)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.animtimeSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.animtimeSpinBox.setDecimals(3)
        self.animtimeSpinBox.setSingleStep(0.1)
        self.animtimeSpinBox.setObjectName("animtimeSpinBox")
        self.hboxlayout.addWidget(self.animtimeSpinBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.hboxlayout.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.parametersTable = QtGui.QTreeView(self.dockWidgetContents_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.parametersTable.setPalette(palette)
        self.parametersTable.setMidLineWidth(1)
        self.parametersTable.setTabKeyNavigation(True)
        self.parametersTable.setDragEnabled(True)
        self.parametersTable.setAlternatingRowColors(True)
        self.parametersTable.setRootIsDecorated(False)
        self.parametersTable.setAnimated(True)
        self.parametersTable.setAllColumnsShowFocus(True)
        self.parametersTable.setObjectName("parametersTable")
        self.verticalLayout_5.addWidget(self.parametersTable)
        self.parametersDock.setWidget(self.dockWidgetContents_3)
        self.gridLayout_3.addWidget(self.parametersDock, 0, 2, 4, 1)
        self.descriptionDock = QtGui.QDockWidget(self.centralwidget)
        self.descriptionDock.setObjectName("descriptionDock")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lpytoolbox = QtGui.QToolBox(self.dockWidgetContents_4)
        self.lpytoolbox.setMidLineWidth(1)
        self.lpytoolbox.setObjectName("lpytoolbox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 139, 191))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.descriptionEdit = QtGui.QTextEdit(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setAcceptRichText(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_2.addWidget(self.descriptionEdit)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.referenceEdit = QtGui.QTextEdit(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceEdit.sizePolicy().hasHeightForWidth())
        self.referenceEdit.setSizePolicy(sizePolicy)
        self.referenceEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.referenceEdit.setAcceptRichText(False)
        self.referenceEdit.setObjectName("referenceEdit")
        self.verticalLayout_2.addWidget(self.referenceEdit)
        self.lpytoolbox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 123, 230))
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.authorsEdit = QtGui.QTextEdit(self.page_2)
        self.authorsEdit.setObjectName("authorsEdit")
        self.verticalLayout.addWidget(self.authorsEdit)
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.intitutesEdit = QtGui.QTextEdit(self.page_2)
        self.intitutesEdit.setObjectName("intitutesEdit")
        self.verticalLayout.addWidget(self.intitutesEdit)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.copyrightEdit = QtGui.QTextEdit(self.page_2)
        self.copyrightEdit.setObjectName("copyrightEdit")
        self.verticalLayout.addWidget(self.copyrightEdit)
        self.lpytoolbox.addItem(self.page_2, "")
        self.verticalLayout_6.addWidget(self.lpytoolbox)
        self.descriptionDock.setWidget(self.dockWidgetContents_4)
        self.gridLayout_3.addWidget(self.descriptionDock, 0, 3, 4, 1)
        self.helpDock = QtGui.QDockWidget(self.centralwidget)
        self.helpDock.setFloating(False)
        self.helpDock.setObjectName("helpDock")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.helpDisplay = QtGui.QTextBrowser(self.dockWidgetContents_5)
        self.helpDisplay.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.helpDisplay.setAcceptRichText(True)
        self.helpDisplay.setObjectName("helpDisplay")
        self.verticalLayout_7.addWidget(self.helpDisplay)
        self.helpDock.setWidget(self.dockWidgetContents_5)
        self.gridLayout_3.addWidget(self.helpDock, 0, 4, 4, 1)
        self.frameGoto = QtGui.QFrame(self.centralwidget)
        self.frameGoto.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameGoto.setFrameShadow(QtGui.QFrame.Raised)
        self.frameGoto.setObjectName("frameGoto")
        self._2 = QtGui.QGridLayout(self.frameGoto)
        self._2.setMargin(0)
        self._2.setHorizontalSpacing(3)
        self._2.setObjectName("_2")
        self.closeGoto = QtGui.QToolButton(self.frameGoto)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeGoto.setPalette(palette)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/closetab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeGoto.setIcon(icon1)
        self.closeGoto.setAutoRaise(True)
        self.closeGoto.setObjectName("closeGoto")
        self._2.addWidget(self.closeGoto, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.frameGoto)
        self.label_10.setObjectName("label_10")
        self._2.addWidget(self.label_10, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(61, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2, 0, 3, 1, 1)
        self.gotoEdit = QtGui.QLineEdit(self.frameGoto)
        self.gotoEdit.setObjectName("gotoEdit")
        self._2.addWidget(self.gotoEdit, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frameGoto, 1, 5, 1, 1)
        self.frameFind = QtGui.QFrame(self.centralwidget)
        self.frameFind.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFind.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFind.setObjectName("frameFind")
        self.gridlayout = QtGui.QGridLayout(self.frameFind)
        self.gridlayout.setMargin(0)
        self.gridlayout.setHorizontalSpacing(3)
        self.gridlayout.setObjectName("gridlayout")
        self.closeFind = QtGui.QToolButton(self.frameFind)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeFind.setPalette(palette)
        self.closeFind.setIcon(icon1)
        self.closeFind.setAutoRaise(True)
        self.closeFind.setObjectName("closeFind")
        self.gridlayout.addWidget(self.closeFind, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frameFind)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.findEdit = QtGui.QLineEdit(self.frameFind)
        self.findEdit.setObjectName("findEdit")
        self.gridlayout.addWidget(self.findEdit, 0, 2, 1, 1)
        self.findNextButton = QtGui.QPushButton(self.frameFind)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findNextButton.setIcon(icon2)
        self.findNextButton.setObjectName("findNextButton")
        self.gridlayout.addWidget(self.findNextButton, 0, 3, 1, 1)
        self.findPreviousButton = QtGui.QPushButton(self.frameFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findPreviousButton.sizePolicy().hasHeightForWidth())
        self.findPreviousButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findPreviousButton.setIcon(icon3)
        self.findPreviousButton.setObjectName("findPreviousButton")
        self.gridlayout.addWidget(self.findPreviousButton, 0, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(61, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(161, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 1, 0, 1, 3)
        self.matchCaseButton = QtGui.QRadioButton(self.frameFind)
        self.matchCaseButton.setAutoExclusive(False)
        self.matchCaseButton.setObjectName("matchCaseButton")
        self.gridlayout.addWidget(self.matchCaseButton, 1, 3, 1, 1)
        self.wholeWordButton = QtGui.QRadioButton(self.frameFind)
        self.wholeWordButton.setAutoExclusive(False)
        self.wholeWordButton.setObjectName("wholeWordButton")
        self.gridlayout.addWidget(self.wholeWordButton, 1, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 1, 5, 1, 1)
        self.gridLayout_3.addWidget(self.frameFind, 2, 5, 1, 1)
        self.frameReplace = QtGui.QFrame(self.centralwidget)
        self.frameReplace.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameReplace.setFrameShadow(QtGui.QFrame.Raised)
        self.frameReplace.setObjectName("frameReplace")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.frameReplace)
        self.hboxlayout1.setSpacing(3)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_9 = QtGui.QLabel(self.frameReplace)
        self.label_9.setObjectName("label_9")
        self.hboxlayout1.addWidget(self.label_9)
        self.replaceEdit = QtGui.QLineEdit(self.frameReplace)
        self.replaceEdit.setObjectName("replaceEdit")
        self.hboxlayout1.addWidget(self.replaceEdit)
        self.replaceButton = QtGui.QPushButton(self.frameReplace)
        self.replaceButton.setObjectName("replaceButton")
        self.hboxlayout1.addWidget(self.replaceButton)
        self.replaceAllButton = QtGui.QPushButton(self.frameReplace)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.hboxlayout1.addWidget(self.replaceAllButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem6)
        self.gridLayout_3.addWidget(self.frameReplace, 3, 5, 1, 1)
        self.interpreterDock = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreterDock.sizePolicy().hasHeightForWidth())
        self.interpreterDock.setSizePolicy(sizePolicy)
        self.interpreterDock.setFloating(False)
        self.interpreterDock.setObjectName("interpreterDock")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.vboxlayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.interpreterDock.setWidget(self.dockWidgetContents)
        self.gridLayout_3.addWidget(self.interpreterDock, 4, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.documentNames = LpyTabBar(self.frame)
        self.documentNames.setObjectName("documentNames")
        self.gridLayout.addWidget(self.documentNames, 0, 0, 1, 1)
        self.codeeditor = LpyCodeEditor(self.frame)
        self.codeeditor.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.codeeditor.setFont(font)
        self.codeeditor.setFrameShape(QtGui.QFrame.WinPanel)
        self.codeeditor.setTabStopWidth(20)
        self.codeeditor.setObjectName("codeeditor")
        self.gridLayout.addWidget(self.codeeditor, 1, 0, 1, 3)
        self.documentNamesMore = LpyTabBarNeighbor(self.frame)
        self.documentNamesMore.setObjectName("documentNamesMore")
        self.gridLayout.addWidget(self.documentNamesMore, 0, 1, 1, 1)
        self.documentNamesMore2 = LpyTabBarNeighbor(self.frame)
        self.documentNamesMore2.setObjectName("documentNamesMore2")
        self.gridLayout.addWidget(self.documentNamesMore2, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.menubar.setObjectName("menubar")
        self.menuL_systems = QtGui.QMenu(self.menubar)
        self.menuL_systems.setObjectName("menuL_systems")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecents = QtGui.QMenu(self.menuFile)
        self.menuRecents.setObjectName("menuRecents")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.FileBar = QtGui.QToolBar(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileBar.setWindowIcon(icon4)
        self.FileBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.FileBar.setObjectName("FileBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.FileBar)
        self.LsytemBar = QtGui.QToolBar(MainWindow)
        self.LsytemBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.LsytemBar.setObjectName("LsytemBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.LsytemBar)
        self.profilerDock = QtGui.QDockWidget(MainWindow)
        self.profilerDock.setObjectName("profilerDock")
        self.dockWidgetContents_9 = QtGui.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents_9)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setMargin(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.profileView = QtGui.QTreeView(self.dockWidgetContents_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(244, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.profileView.setPalette(palette)
        self.profileView.setAlternatingRowColors(True)
        self.profileView.setSortingEnabled(True)
        self.profileView.setObjectName("profileView")
        self.verticalLayout_9.addWidget(self.profileView)
        self.profilerDock.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.profilerDock)
        self.editToolBar = QtGui.QToolBar(MainWindow)
        self.editToolBar.setObjectName("editToolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.editToolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setIcon(icon6)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icons/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon8)
        self.actionRun.setObjectName("actionRun")
        self.actionAnimate = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnimate.setIcon(icon9)
        self.actionAnimate.setObjectName("actionAnimate")
        self.actionStep = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icons/step.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep.setIcon(icon10)
        self.actionStep.setObjectName("actionStep")
        self.actionRewind = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icons/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRewind.setIcon(icon11)
        self.actionRewind.setObjectName("actionRewind")
        self.actionNew = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/icons/filenew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon12)
        self.actionNew.setObjectName("actionNew")
        self.actionUndo = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/icons/editundo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon13)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/icons/editredo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon14)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCopy = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/icons/editcopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon15)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/icons/editcut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon16)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/icons/editpaste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon17)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionFind = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/icons/editfind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon18)
        self.actionFind.setObjectName("actionFind")
        self.actionPythonShell = QtGui.QAction(MainWindow)
        self.actionPythonShell.setObjectName("actionPythonShell")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionUseThread = QtGui.QAction(MainWindow)
        self.actionUseThread.setCheckable(True)
        self.actionUseThread.setObjectName("actionUseThread")
        self.actionFitAnimationView = QtGui.QAction(MainWindow)
        self.actionFitAnimationView.setCheckable(True)
        self.actionFitAnimationView.setObjectName("actionFitAnimationView")
        self.actionClose = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/images/icons/fileclose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon19)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtGui.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutVPlants = QtGui.QAction(MainWindow)
        self.actionAboutVPlants.setObjectName("actionAboutVPlants")
        self.actionClearShell = QtGui.QAction(MainWindow)
        self.actionClearShell.setObjectName("actionClearShell")
        self.actionSyntax = QtGui.QAction(MainWindow)
        self.actionSyntax.setCheckable(True)
        self.actionSyntax.setObjectName("actionSyntax")
        self.actionComment = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/images/icons/next-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionComment.setIcon(icon20)
        self.actionComment.setObjectName("actionComment")
        self.actionUncomment = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/images/icons/prev-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUncomment.setIcon(icon21)
        self.actionUncomment.setObjectName("actionUncomment")
        self.actionInsertTab = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/images/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertTab.setIcon(icon22)
        self.actionInsertTab.setObjectName("actionInsertTab")
        self.actionRemoveTab = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/images/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveTab.setIcon(icon23)
        self.actionRemoveTab.setObjectName("actionRemoveTab")
        self.actionReplace = QtGui.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionParseDebug = QtGui.QAction(MainWindow)
        self.actionParseDebug.setCheckable(True)
        self.actionParseDebug.setObjectName("actionParseDebug")
        self.actionStop = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/images/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon24)
        self.actionStop.setObjectName("actionStop")
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/images/icons/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon25)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtGui.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/images/icons/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon26)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionNoZoom = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/images/icons/resetzoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNoZoom.setIcon(icon27)
        self.actionNoZoom.setObjectName("actionNoZoom")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionTabHightlight = QtGui.QAction(MainWindow)
        self.actionTabHightlight.setCheckable(True)
        self.actionTabHightlight.setObjectName("actionTabHightlight")
        self.actionSaveAll = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/images/icons/filesaveall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAll.setIcon(icon28)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionGoto = QtGui.QAction(MainWindow)
        self.actionGoto.setObjectName("actionGoto")
        self.actionDebug = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/images/icons/play-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDebug.setIcon(icon29)
        self.actionDebug.setObjectName("actionDebug")
        self.actionIterateTo = QtGui.QAction(MainWindow)
        self.actionIterateTo.setIcon(icon8)
        self.actionIterateTo.setObjectName("actionIterateTo")
        self.actionNextIterate = QtGui.QAction(MainWindow)
        self.actionNextIterate.setIcon(icon8)
        self.actionNextIterate.setObjectName("actionNextIterate")
        self.actionAutoRun = QtGui.QAction(MainWindow)
        self.actionAutoRun.setCheckable(True)
        self.actionAutoRun.setObjectName("actionAutoRun")
        self.actionProfile = QtGui.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/images/icons/play-yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProfile.setIcon(icon30)
        self.actionProfile.setObjectName("actionProfile")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/images/icons/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon31)
        self.actionPrint.setObjectName("actionPrint")
        self.menuL_systems.addAction(self.actionRun)
        self.menuL_systems.addAction(self.actionAnimate)
        self.menuL_systems.addSeparator()
        self.menuL_systems.addAction(self.actionStep)
        self.menuL_systems.addAction(self.actionRewind)
        self.menuL_systems.addAction(self.actionStop)
        self.menuL_systems.addSeparator()
        self.menuL_systems.addAction(self.actionIterateTo)
        self.menuL_systems.addAction(self.actionNextIterate)
        self.menuL_systems.addSeparator()
        self.menuL_systems.addAction(self.actionAutoRun)
        self.menuL_systems.addSeparator()
        self.menuL_systems.addAction(self.actionDebug)
        self.menuL_systems.addAction(self.actionProfile)
        self.menuRecents.addAction(self.actionClear)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionSaveAll)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecents.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionComment)
        self.menuEdit.addAction(self.actionUncomment)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionInsertTab)
        self.menuEdit.addAction(self.actionRemoveTab)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionGoto)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuHelp.addAction(self.actionAboutVPlants)
        self.menuHelp.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionNoZoom)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSyntax)
        self.menuView.addAction(self.actionTabHightlight)
        self.menuView.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuL_systems.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.FileBar.addAction(self.actionNew)
        self.FileBar.addAction(self.actionOpen)
        self.FileBar.addAction(self.actionSave)
        self.FileBar.addAction(self.actionSaveAll)
        self.FileBar.addAction(self.actionClose)
        self.LsytemBar.addAction(self.actionRun)
        self.LsytemBar.addAction(self.actionAnimate)
        self.LsytemBar.addAction(self.actionStop)
        self.LsytemBar.addAction(self.actionRewind)
        self.LsytemBar.addAction(self.actionStep)
        self.LsytemBar.addAction(self.actionDebug)
        self.LsytemBar.addAction(self.actionProfile)
        self.editToolBar.addAction(self.actionUndo)
        self.editToolBar.addAction(self.actionRedo)
        self.editToolBar.addAction(self.actionCopy)
        self.editToolBar.addAction(self.actionCut)
        self.editToolBar.addAction(self.actionPaste)
        self.editToolBar.addAction(self.actionFind)

        self.retranslateUi(MainWindow)
        self.lpytoolbox.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionReplace, QtCore.SIGNAL("triggered()"), self.frameFind.show)
        QtCore.QObject.connect(self.actionPaste, QtCore.SIGNAL("triggered()"), self.codeeditor.paste)
        QtCore.QObject.connect(self.actionSelect_All, QtCore.SIGNAL("triggered()"), self.codeeditor.selectAll)
        QtCore.QObject.connect(self.closeFind, QtCore.SIGNAL("pressed()"), self.frameReplace.hide)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), self.frameReplace.hide)
        QtCore.QObject.connect(self.actionReplace, QtCore.SIGNAL("triggered()"), self.frameReplace.show)
        QtCore.QObject.connect(self.actionReplace, QtCore.SIGNAL("triggered()"), self.findEdit.setFocus)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), self.findEdit.selectAll)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), self.findEdit.setFocus)
        QtCore.QObject.connect(self.codeeditor, QtCore.SIGNAL("redoAvailable(bool)"), self.actionRedo.setEnabled)
        QtCore.QObject.connect(self.closeFind, QtCore.SIGNAL("pressed()"), self.frameFind.hide)
        QtCore.QObject.connect(self.actionCut, QtCore.SIGNAL("triggered()"), self.codeeditor.cut)
        QtCore.QObject.connect(self.actionUndo, QtCore.SIGNAL("triggered()"), self.codeeditor.undo)
        QtCore.QObject.connect(self.actionCopy, QtCore.SIGNAL("triggered()"), self.codeeditor.copy)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), self.frameFind.show)
        QtCore.QObject.connect(self.actionRedo, QtCore.SIGNAL("triggered()"), self.codeeditor.redo)
        QtCore.QObject.connect(self.codeeditor, QtCore.SIGNAL("undoAvailable(bool)"), self.actionUndo.setEnabled)
        QtCore.QObject.connect(self.closeGoto, QtCore.SIGNAL("pressed()"), self.frameGoto.hide)
        QtCore.QObject.connect(self.actionGoto, QtCore.SIGNAL("triggered()"), self.frameGoto.show)
        QtCore.QObject.connect(self.gotoEdit, QtCore.SIGNAL("returnPressed()"), self.frameGoto.hide)
        QtCore.QObject.connect(self.actionGoto, QtCore.SIGNAL("triggered()"), self.gotoEdit.setFocus)
        QtCore.QObject.connect(self.actionGoto, QtCore.SIGNAL("triggered()"), self.frameFind.hide)
        QtCore.QObject.connect(self.actionGoto, QtCore.SIGNAL("triggered()"), self.frameReplace.hide)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), self.frameGoto.hide)
        QtCore.QObject.connect(self.actionReplace, QtCore.SIGNAL("triggered()"), self.frameGoto.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.codeeditor, self.closeFind)
        MainWindow.setTabOrder(self.closeFind, self.findEdit)
        MainWindow.setTabOrder(self.findEdit, self.replaceEdit)
        MainWindow.setTabOrder(self.replaceEdit, self.findNextButton)
        MainWindow.setTabOrder(self.findNextButton, self.findPreviousButton)
        MainWindow.setTabOrder(self.findPreviousButton, self.replaceButton)
        MainWindow.setTabOrder(self.replaceButton, self.replaceAllButton)
        MainWindow.setTabOrder(self.replaceAllButton, self.matchCaseButton)
        MainWindow.setTabOrder(self.matchCaseButton, self.wholeWordButton)
        MainWindow.setTabOrder(self.wholeWordButton, self.animtimeSpinBox)
        MainWindow.setTabOrder(self.animtimeSpinBox, self.animtimestep)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "L-Py", None, QtGui.QApplication.UnicodeUTF8))
        self.scalarDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Scalars", None, QtGui.QApplication.UnicodeUTF8))
        self.materialDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Color Map", None, QtGui.QApplication.UnicodeUTF8))
        self.parametersDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Time Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "s.", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "References", None, QtGui.QApplication.UnicodeUTF8))
        self.lpytoolbox.setItemText(self.lpytoolbox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Institutes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Copyright", None, QtGui.QApplication.UnicodeUTF8))
        self.lpytoolbox.setItemText(self.lpytoolbox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.helpDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Go to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.findNextButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.findPreviousButton.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.matchCaseButton.setText(QtGui.QApplication.translate("MainWindow", "Match Case", None, QtGui.QApplication.UnicodeUTF8))
        self.wholeWordButton.setText(QtGui.QApplication.translate("MainWindow", "Whole word", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceButton.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceAllButton.setText(QtGui.QApplication.translate("MainWindow", "Rep. All", None, QtGui.QApplication.UnicodeUTF8))
        self.interpreterDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Python Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.menuL_systems.setTitle(QtGui.QApplication.translate("MainWindow", "L-systems", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecents.setTitle(QtGui.QApplication.translate("MainWindow", "Recents", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.FileBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "File Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.LsytemBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lsystem Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.profilerDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.editToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Edit Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnimate.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStep.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStep.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRewind.setText(QtGui.QApplication.translate("MainWindow", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPythonShell.setText(QtGui.QApplication.translate("MainWindow", "Python Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUseThread.setText(QtGui.QApplication.translate("MainWindow", "Use Thread", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitAnimationView.setText(QtGui.QApplication.translate("MainWindow", "Fit Animate View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutVPlants.setText(QtGui.QApplication.translate("MainWindow", "About V. Plants", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearShell.setText(QtGui.QApplication.translate("MainWindow", "Clear Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSyntax.setText(QtGui.QApplication.translate("MainWindow", "Syntax Hightlight", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setText(QtGui.QApplication.translate("MainWindow", "Comment Block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUncomment.setText(QtGui.QApplication.translate("MainWindow", "Uncomment Block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertTab.setText(QtGui.QApplication.translate("MainWindow", "Insert Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveTab.setText(QtGui.QApplication.translate("MainWindow", "Remove Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParseDebug.setText(QtGui.QApplication.translate("MainWindow", "Parse Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoZoom.setText(QtGui.QApplication.translate("MainWindow", "Zoom 1:1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabHightlight.setText(QtGui.QApplication.translate("MainWindow", "Tab Hightlight", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAll.setText(QtGui.QApplication.translate("MainWindow", "Save All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoto.setText(QtGui.QApplication.translate("MainWindow", "Go to line ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoto.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIterateTo.setText(QtGui.QApplication.translate("MainWindow", "Iterate n times", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextIterate.setText(QtGui.QApplication.translate("MainWindow", "Next n iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextIterate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRun.setText(QtGui.QApplication.translate("MainWindow", "Auto-Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProfile.setText(QtGui.QApplication.translate("MainWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))

from lpycodeeditor import LpyCodeEditor
from materialeditor import MaterialEditor
from scalareditor import ScalarEditor
from lpytabbar import LpyTabBar, LpyTabBarNeighbor
import lpyresources_rc
