# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/fboudon/Develop/oagit/lpy/src/openalea/lpy/gui/lpyprefwidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreferenceDialog(object):
    def setupUi(self, PreferenceDialog):
        PreferenceDialog.setObjectName(_fromUtf8("PreferenceDialog"))
        PreferenceDialog.resize(315, 306)
        self.verticalLayout_4 = QtGui.QVBoxLayout(PreferenceDialog)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.prefTab = QtGui.QTabWidget(PreferenceDialog)
        self.prefTab.setObjectName(_fromUtf8("prefTab"))
        self.tabAppearance = QtGui.QWidget()
        self.tabAppearance.setObjectName(_fromUtf8("tabAppearance"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAppearance)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tabAppearance)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(95, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolbarAppEdit = QtGui.QComboBox(self.groupBox)
        self.toolbarAppEdit.setObjectName(_fromUtf8("toolbarAppEdit"))
        self.toolbarAppEdit.addItem(_fromUtf8(""))
        self.toolbarAppEdit.addItem(_fromUtf8(""))
        self.toolbarAppEdit.addItem(_fromUtf8(""))
        self.toolbarAppEdit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.toolbarAppEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabAppearance)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(52, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.fontFamilyEdit = QtGui.QFontComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        self.fontFamilyEdit.setCurrentFont(font)
        self.fontFamilyEdit.setObjectName(_fromUtf8("fontFamilyEdit"))
        self.gridLayout.addWidget(self.fontFamilyEdit, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(52, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.fontSizeEdit = QtGui.QSpinBox(self.groupBox_2)
        self.fontSizeEdit.setMinimum(6)
        self.fontSizeEdit.setMaximum(20)
        self.fontSizeEdit.setProperty("value", 8)
        self.fontSizeEdit.setObjectName(_fromUtf8("fontSizeEdit"))
        self.gridLayout.addWidget(self.fontSizeEdit, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem3 = QtGui.QSpacerItem(20, 22, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.prefTab.addTab(self.tabAppearance, _fromUtf8(""))
        self.tabEditing = QtGui.QWidget()
        self.tabEditing.setObjectName(_fromUtf8("tabEditing"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabEditing)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabEditing)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spaceForTabEdit = QtGui.QCheckBox(self.groupBox_4)
        self.spaceForTabEdit.setObjectName(_fromUtf8("spaceForTabEdit"))
        self.gridLayout_2.addWidget(self.spaceForTabEdit, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(143, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.tabSizeEdit = QtGui.QSpinBox(self.groupBox_4)
        self.tabSizeEdit.setMinimum(1)
        self.tabSizeEdit.setProperty("value", 2)
        self.tabSizeEdit.setObjectName(_fromUtf8("tabSizeEdit"))
        self.gridLayout_2.addWidget(self.tabSizeEdit, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem5 = QtGui.QSpacerItem(20, 90, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.prefTab.addTab(self.tabEditing, _fromUtf8(""))
        self.tabFile = QtGui.QWidget()
        self.tabFile.setObjectName(_fromUtf8("tabFile"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabFile)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.tabFile)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(123, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.historySizeEdit = QtGui.QSpinBox(self.tabFile)
        self.historySizeEdit.setMinimum(1)
        self.historySizeEdit.setProperty("value", 50)
        self.historySizeEdit.setObjectName(_fromUtf8("historySizeEdit"))
        self.gridLayout_3.addWidget(self.historySizeEdit, 0, 2, 1, 1)
        self.startupReloadEdit = QtGui.QCheckBox(self.tabFile)
        self.startupReloadEdit.setChecked(True)
        self.startupReloadEdit.setObjectName(_fromUtf8("startupReloadEdit"))
        self.gridLayout_3.addWidget(self.startupReloadEdit, 1, 0, 1, 2)
        self.fileMonitoringEdit = QtGui.QCheckBox(self.tabFile)
        self.fileMonitoringEdit.setChecked(True)
        self.fileMonitoringEdit.setObjectName(_fromUtf8("fileMonitoringEdit"))
        self.gridLayout_3.addWidget(self.fileMonitoringEdit, 2, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.tabFile)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.fileBackupEdit = QtGui.QRadioButton(self.groupBox_7)
        self.fileBackupEdit.setAutoExclusive(False)
        self.fileBackupEdit.setObjectName(_fromUtf8("fileBackupEdit"))
        self.verticalLayout.addWidget(self.fileBackupEdit)
        self.codeBackupEdit = QtGui.QRadioButton(self.groupBox_7)
        self.codeBackupEdit.setAutoExclusive(False)
        self.codeBackupEdit.setObjectName(_fromUtf8("codeBackupEdit"))
        self.verticalLayout.addWidget(self.codeBackupEdit)
        self.gridLayout_3.addWidget(self.groupBox_7, 3, 0, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 4, 1, 1, 1)
        self.prefTab.addTab(self.tabFile, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pycodeDebugEdit = QtGui.QCheckBox(self.groupBox_6)
        self.pycodeDebugEdit.setObjectName(_fromUtf8("pycodeDebugEdit"))
        self.horizontalLayout_4.addWidget(self.pycodeDebugEdit)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.gccPathEdit = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gccPathEdit.sizePolicy().hasHeightForWidth())
        self.gccPathEdit.setSizePolicy(sizePolicy)
        self.gccPathEdit.setObjectName(_fromUtf8("gccPathEdit"))
        self.horizontalLayout_5.addWidget(self.gccPathEdit)
        self.gccPathButton = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gccPathButton.sizePolicy().hasHeightForWidth())
        self.gccPathButton.setSizePolicy(sizePolicy)
        self.gccPathButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.gccPathButton.setObjectName(_fromUtf8("gccPathButton"))
        self.horizontalLayout_5.addWidget(self.gccPathButton)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        spacerItem8 = QtGui.QSpacerItem(18, 54, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.prefTab.addTab(self.tab, _fromUtf8(""))
        self.tabExecution = QtGui.QWidget()
        self.tabExecution.setObjectName(_fromUtf8("tabExecution"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabExecution)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabExecution)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.useThreadEdit = QtGui.QCheckBox(self.groupBox_3)
        self.useThreadEdit.setObjectName(_fromUtf8("useThreadEdit"))
        self.horizontalLayout_2.addWidget(self.useThreadEdit)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.visuCheckBoxLayout = QtGui.QGroupBox(self.tabExecution)
        self.visuCheckBoxLayout.setObjectName(_fromUtf8("visuCheckBoxLayout"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.visuCheckBoxLayout)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.fitViewEdit = QtGui.QCheckBox(self.visuCheckBoxLayout)
        self.fitViewEdit.setChecked(True)
        self.fitViewEdit.setObjectName(_fromUtf8("fitViewEdit"))
        self.verticalLayout_9.addWidget(self.fitViewEdit)
        self.integratedViewEdit = QtGui.QCheckBox(self.visuCheckBoxLayout)
        self.integratedViewEdit.setObjectName(_fromUtf8("integratedViewEdit"))
        self.verticalLayout_9.addWidget(self.integratedViewEdit)
        self.visuInfoEdit = QtGui.QCheckBox(self.visuCheckBoxLayout)
        self.visuInfoEdit.setObjectName(_fromUtf8("visuInfoEdit"))
        self.verticalLayout_9.addWidget(self.visuInfoEdit)
        self.verticalLayout_3.addWidget(self.visuCheckBoxLayout)
        self.textOutputBox = QtGui.QGroupBox(self.tabExecution)
        self.textOutputBox.setObjectName(_fromUtf8("textOutputBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.textOutputBox)
        self.verticalLayout_10.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.LPyConsoleButton = QtGui.QRadioButton(self.textOutputBox)
        self.LPyConsoleButton.setChecked(True)
        self.LPyConsoleButton.setAutoExclusive(False)
        self.LPyConsoleButton.setObjectName(_fromUtf8("LPyConsoleButton"))
        self.verticalLayout_10.addWidget(self.LPyConsoleButton)
        self.systemConsoleButton = QtGui.QRadioButton(self.textOutputBox)
        self.systemConsoleButton.setChecked(False)
        self.systemConsoleButton.setAutoExclusive(False)
        self.systemConsoleButton.setObjectName(_fromUtf8("systemConsoleButton"))
        self.verticalLayout_10.addWidget(self.systemConsoleButton)
        self.verticalLayout_3.addWidget(self.textOutputBox)
        spacerItem9 = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.prefTab.addTab(self.tabExecution, _fromUtf8(""))
        self.profilingTab = QtGui.QWidget()
        self.profilingTab.setObjectName(_fromUtf8("profilingTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.profilingTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_9 = QtGui.QGroupBox(self.profilingTab)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.profilingAnimatedButton = QtGui.QRadioButton(self.groupBox_9)
        self.profilingAnimatedButton.setObjectName(_fromUtf8("profilingAnimatedButton"))
        self.verticalLayout_7.addWidget(self.profilingAnimatedButton)
        self.profilingFinalPlotButton = QtGui.QRadioButton(self.groupBox_9)
        self.profilingFinalPlotButton.setChecked(True)
        self.profilingFinalPlotButton.setObjectName(_fromUtf8("profilingFinalPlotButton"))
        self.verticalLayout_7.addWidget(self.profilingFinalPlotButton)
        self.profilingNoPlotButton = QtGui.QRadioButton(self.groupBox_9)
        self.profilingNoPlotButton.setObjectName(_fromUtf8("profilingNoPlotButton"))
        self.verticalLayout_7.addWidget(self.profilingNoPlotButton)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        spacerItem10 = QtGui.QSpacerItem(20, 71, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.prefTab.addTab(self.profilingTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.prefTab)
        self.buttonBox = QtGui.QDialogButtonBox(PreferenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(PreferenceDialog)
        self.prefTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreferenceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreferenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferenceDialog)

    def retranslateUi(self, PreferenceDialog):
        PreferenceDialog.setWindowTitle(_translate("PreferenceDialog", "Preferences", None))
        self.groupBox.setTitle(_translate("PreferenceDialog", "ToolBar", None))
        self.label.setText(_translate("PreferenceDialog", "Show", None))
        self.toolbarAppEdit.setItemText(0, _translate("PreferenceDialog", "Icons", None))
        self.toolbarAppEdit.setItemText(1, _translate("PreferenceDialog", "Texts", None))
        self.toolbarAppEdit.setItemText(2, _translate("PreferenceDialog", "Icons and texts", None))
        self.toolbarAppEdit.setItemText(3, _translate("PreferenceDialog", "Texts below icons", None))
        self.groupBox_2.setTitle(_translate("PreferenceDialog", "Text Editor", None))
        self.label_2.setText(_translate("PreferenceDialog", "Font Family", None))
        self.label_3.setText(_translate("PreferenceDialog", "Font Size", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabAppearance), _translate("PreferenceDialog", "Appearance", None))
        self.groupBox_4.setTitle(_translate("PreferenceDialog", "Tabulation", None))
        self.spaceForTabEdit.setText(_translate("PreferenceDialog", "Replace by spaces", None))
        self.label_4.setText(_translate("PreferenceDialog", "Tab size", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabEditing), _translate("PreferenceDialog", "Editing", None))
        self.label_5.setText(_translate("PreferenceDialog", "History max size", None))
        self.startupReloadEdit.setText(_translate("PreferenceDialog", "Reload file at startup", None))
        self.fileMonitoringEdit.setText(_translate("PreferenceDialog", "Check file change on disk.", None))
        self.groupBox_7.setTitle(_translate("PreferenceDialog", "Backup", None))
        self.label_6.setText(_translate("PreferenceDialog", "Create backup file", None))
        self.fileBackupEdit.setText(_translate("PreferenceDialog", "Of previous file before saving", None))
        self.codeBackupEdit.setText(_translate("PreferenceDialog", "Of code before execution", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabFile), _translate("PreferenceDialog", "File", None))
        self.groupBox_6.setTitle(_translate("PreferenceDialog", "Parsing", None))
        self.pycodeDebugEdit.setText(_translate("PreferenceDialog", "Show python code for debug.", None))
        self.groupBox_8.setTitle(_translate("PreferenceDialog", "Cython", None))
        self.label_7.setText(_translate("PreferenceDialog", "GCC Path", None))
        self.gccPathButton.setText(_translate("PreferenceDialog", "...", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tab), _translate("PreferenceDialog", "Compilation", None))
        self.groupBox_3.setTitle(_translate("PreferenceDialog", "Threading", None))
        self.useThreadEdit.setText(_translate("PreferenceDialog", "Use thread (Experimental).", None))
        self.visuCheckBoxLayout.setTitle(_translate("PreferenceDialog", "Visualization", None))
        self.fitViewEdit.setText(_translate("PreferenceDialog", "Fit last view before animation.", None))
        self.integratedViewEdit.setText(_translate("PreferenceDialog", "Integrated viewer", None))
        self.visuInfoEdit.setText(_translate("PreferenceDialog", "Display info at run", None))
        self.textOutputBox.setTitle(_translate("PreferenceDialog", "Text Output", None))
        self.LPyConsoleButton.setText(_translate("PreferenceDialog", "LPy Console", None))
        self.systemConsoleButton.setText(_translate("PreferenceDialog", "System Console", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabExecution), _translate("PreferenceDialog", "Execution", None))
        self.groupBox_9.setTitle(_translate("PreferenceDialog", "Visualisation", None))
        self.profilingAnimatedButton.setText(_translate("PreferenceDialog", "Animated Mode", None))
        self.profilingFinalPlotButton.setText(_translate("PreferenceDialog", "Final plot", None))
        self.profilingNoPlotButton.setText(_translate("PreferenceDialog", "No plot", None))
        self.prefTab.setTabText(self.prefTab.indexOf(self.profilingTab), _translate("PreferenceDialog", "Profiling", None))

