# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Fred\Mes Documents\Develop\vplants\trunk\lpy\src\openalea\lpy\gui\lpyprefwidget.ui'
#
# Created: Mon Aug 11 12:08:32 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PreferenceDialog(object):
    def setupUi(self, PreferenceDialog):
        PreferenceDialog.setObjectName("PreferenceDialog")
        PreferenceDialog.resize(300,274)
        self.verticalLayout_4 = QtGui.QVBoxLayout(PreferenceDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.prefTab = QtGui.QTabWidget(PreferenceDialog)
        self.prefTab.setObjectName("prefTab")
        self.tabAppearance = QtGui.QWidget()
        self.tabAppearance.setGeometry(QtCore.QRect(0,0,276,198))
        self.tabAppearance.setObjectName("tabAppearance")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAppearance)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tabAppearance)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(95,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolbarAppEdit = QtGui.QComboBox(self.groupBox)
        self.toolbarAppEdit.setObjectName("toolbarAppEdit")
        self.horizontalLayout.addWidget(self.toolbarAppEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabAppearance)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2,0,0,1,1)
        spacerItem1 = QtGui.QSpacerItem(52,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1,0,1,1,1)
        self.fontFamilyEdit = QtGui.QFontComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.fontFamilyEdit.setCurrentFont(font)
        self.fontFamilyEdit.setObjectName("fontFamilyEdit")
        self.gridLayout.addWidget(self.fontFamilyEdit,0,2,1,1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3,1,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(52,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2,1,1,1,1)
        self.fontSizeEdit = QtGui.QSpinBox(self.groupBox_2)
        self.fontSizeEdit.setMinimum(6)
        self.fontSizeEdit.setMaximum(20)
        self.fontSizeEdit.setProperty("value",QtCore.QVariant(8))
        self.fontSizeEdit.setObjectName("fontSizeEdit")
        self.gridLayout.addWidget(self.fontSizeEdit,1,2,1,1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem3 = QtGui.QSpacerItem(20,22,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.prefTab.addTab(self.tabAppearance,"")
        self.tabEditing = QtGui.QWidget()
        self.tabEditing.setGeometry(QtCore.QRect(0,0,276,198))
        self.tabEditing.setObjectName("tabEditing")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabEditing)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtGui.QGroupBox(self.tabEditing)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spaceForTabEdit = QtGui.QCheckBox(self.groupBox_4)
        self.spaceForTabEdit.setObjectName("spaceForTabEdit")
        self.gridLayout_2.addWidget(self.spaceForTabEdit,0,0,1,2)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4,1,0,1,1)
        spacerItem4 = QtGui.QSpacerItem(143,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4,1,1,1,1)
        self.tabSizeEdit = QtGui.QSpinBox(self.groupBox_4)
        self.tabSizeEdit.setMinimum(1)
        self.tabSizeEdit.setProperty("value",QtCore.QVariant(2))
        self.tabSizeEdit.setObjectName("tabSizeEdit")
        self.gridLayout_2.addWidget(self.tabSizeEdit,1,2,1,1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem5 = QtGui.QSpacerItem(20,90,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.prefTab.addTab(self.tabEditing,"")
        self.tabFile = QtGui.QWidget()
        self.tabFile.setGeometry(QtCore.QRect(180,262,952,688))
        self.tabFile.setObjectName("tabFile")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabFile)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.tabFile)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5,0,0,1,1)
        spacerItem6 = QtGui.QSpacerItem(123,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6,0,1,1,1)
        self.historySizeEdit = QtGui.QSpinBox(self.tabFile)
        self.historySizeEdit.setMinimum(1)
        self.historySizeEdit.setProperty("value",QtCore.QVariant(50))
        self.historySizeEdit.setObjectName("historySizeEdit")
        self.gridLayout_3.addWidget(self.historySizeEdit,0,2,1,1)
        self.startupReloadEdit = QtGui.QCheckBox(self.tabFile)
        self.startupReloadEdit.setChecked(True)
        self.startupReloadEdit.setObjectName("startupReloadEdit")
        self.gridLayout_3.addWidget(self.startupReloadEdit,1,0,1,2)
        self.fileMonitoringEdit = QtGui.QCheckBox(self.tabFile)
        self.fileMonitoringEdit.setChecked(True)
        self.fileMonitoringEdit.setObjectName("fileMonitoringEdit")
        self.gridLayout_3.addWidget(self.fileMonitoringEdit,2,0,1,2)
        self.groupBox_7 = QtGui.QGroupBox(self.tabFile)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.fileBackupEdit = QtGui.QRadioButton(self.groupBox_7)
        self.fileBackupEdit.setAutoExclusive(False)
        self.fileBackupEdit.setObjectName("fileBackupEdit")
        self.verticalLayout.addWidget(self.fileBackupEdit)
        self.codeBackupEdit = QtGui.QRadioButton(self.groupBox_7)
        self.codeBackupEdit.setAutoExclusive(False)
        self.codeBackupEdit.setObjectName("codeBackupEdit")
        self.verticalLayout.addWidget(self.codeBackupEdit)
        self.gridLayout_3.addWidget(self.groupBox_7,3,0,1,3)
        spacerItem7 = QtGui.QSpacerItem(20,3,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7,4,1,1,1)
        self.prefTab.addTab(self.tabFile,"")
        self.tabExecution = QtGui.QWidget()
        self.tabExecution.setGeometry(QtCore.QRect(4,30,276,198))
        self.tabExecution.setObjectName("tabExecution")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabExecution)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_6 = QtGui.QGroupBox(self.tabExecution)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pycodeDebugEdit = QtGui.QCheckBox(self.groupBox_6)
        self.pycodeDebugEdit.setObjectName("pycodeDebugEdit")
        self.horizontalLayout_4.addWidget(self.pycodeDebugEdit)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_3 = QtGui.QGroupBox(self.tabExecution)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.useThreadEdit = QtGui.QCheckBox(self.groupBox_3)
        self.useThreadEdit.setObjectName("useThreadEdit")
        self.horizontalLayout_2.addWidget(self.useThreadEdit)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.tabExecution)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fitViewEdit = QtGui.QCheckBox(self.groupBox_5)
        self.fitViewEdit.setChecked(True)
        self.fitViewEdit.setObjectName("fitViewEdit")
        self.horizontalLayout_3.addWidget(self.fitViewEdit)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        spacerItem8 = QtGui.QSpacerItem(20,3,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.prefTab.addTab(self.tabExecution,"")
        self.verticalLayout_4.addWidget(self.prefTab)
        self.buttonBox = QtGui.QDialogButtonBox(PreferenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(PreferenceDialog)
        self.prefTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),PreferenceDialog.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),PreferenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferenceDialog)

    def retranslateUi(self, PreferenceDialog):
        PreferenceDialog.setWindowTitle(QtGui.QApplication.translate("PreferenceDialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PreferenceDialog", "ToolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferenceDialog", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarAppEdit.addItem(QtGui.QApplication.translate("PreferenceDialog", "Icons", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarAppEdit.addItem(QtGui.QApplication.translate("PreferenceDialog", "Texts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarAppEdit.addItem(QtGui.QApplication.translate("PreferenceDialog", "Icons and texts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarAppEdit.addItem(QtGui.QApplication.translate("PreferenceDialog", "Texts below icons", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Text Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferenceDialog", "Font Family", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PreferenceDialog", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabAppearance), QtGui.QApplication.translate("PreferenceDialog", "Appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Tabulation", None, QtGui.QApplication.UnicodeUTF8))
        self.spaceForTabEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Replace by spaces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PreferenceDialog", "Tab size", None, QtGui.QApplication.UnicodeUTF8))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabEditing), QtGui.QApplication.translate("PreferenceDialog", "Editing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PreferenceDialog", "History max size", None, QtGui.QApplication.UnicodeUTF8))
        self.startupReloadEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Reload file at startup", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMonitoringEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Check file change on disk.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PreferenceDialog", "Create backup file", None, QtGui.QApplication.UnicodeUTF8))
        self.fileBackupEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Of previous file before saving", None, QtGui.QApplication.UnicodeUTF8))
        self.codeBackupEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Of code before execution", None, QtGui.QApplication.UnicodeUTF8))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabFile), QtGui.QApplication.translate("PreferenceDialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Parsing", None, QtGui.QApplication.UnicodeUTF8))
        self.pycodeDebugEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Show python code for debug.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Threading", None, QtGui.QApplication.UnicodeUTF8))
        self.useThreadEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Use thread (Experimental).", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PreferenceDialog", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.fitViewEdit.setText(QtGui.QApplication.translate("PreferenceDialog", "Fit last view before animation.", None, QtGui.QApplication.UnicodeUTF8))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabExecution), QtGui.QApplication.translate("PreferenceDialog", "Execution", None, QtGui.QApplication.UnicodeUTF8))

