# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/fboudon/Develop/oagit/lpy/src/openalea/lpy/gui/lpyprefwidget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferenceDialog(object):
    def setupUi(self, PreferenceDialog):
        PreferenceDialog.setObjectName("PreferenceDialog")
        PreferenceDialog.resize(315, 306)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(PreferenceDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.prefTab = QtWidgets.QTabWidget(PreferenceDialog)
        self.prefTab.setObjectName("prefTab")
        self.tabAppearance = QtWidgets.QWidget()
        self.tabAppearance.setObjectName("tabAppearance")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabAppearance)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tabAppearance)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolbarAppEdit = QtWidgets.QComboBox(self.groupBox)
        self.toolbarAppEdit.setObjectName("toolbarAppEdit")
        self.toolbarAppEdit.addItem("")
        self.toolbarAppEdit.addItem("")
        self.toolbarAppEdit.addItem("")
        self.toolbarAppEdit.addItem("")
        self.horizontalLayout.addWidget(self.toolbarAppEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabAppearance)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.fontFamilyEdit = QtWidgets.QFontComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.fontFamilyEdit.setCurrentFont(font)
        self.fontFamilyEdit.setObjectName("fontFamilyEdit")
        self.gridLayout.addWidget(self.fontFamilyEdit, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.fontSizeEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.fontSizeEdit.setMinimum(6)
        self.fontSizeEdit.setMaximum(20)
        self.fontSizeEdit.setProperty("value", 8)
        self.fontSizeEdit.setObjectName("fontSizeEdit")
        self.gridLayout.addWidget(self.fontSizeEdit, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.prefTab.addTab(self.tabAppearance, "")
        self.tabEditing = QtWidgets.QWidget()
        self.tabEditing.setObjectName("tabEditing")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabEditing)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabEditing)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spaceForTabEdit = QtWidgets.QCheckBox(self.groupBox_4)
        self.spaceForTabEdit.setObjectName("spaceForTabEdit")
        self.gridLayout_2.addWidget(self.spaceForTabEdit, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(143, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.tabSizeEdit = QtWidgets.QSpinBox(self.groupBox_4)
        self.tabSizeEdit.setMinimum(1)
        self.tabSizeEdit.setProperty("value", 2)
        self.tabSizeEdit.setObjectName("tabSizeEdit")
        self.gridLayout_2.addWidget(self.tabSizeEdit, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.prefTab.addTab(self.tabEditing, "")
        self.tabFile = QtWidgets.QWidget()
        self.tabFile.setObjectName("tabFile")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabFile)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tabFile)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(123, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.historySizeEdit = QtWidgets.QSpinBox(self.tabFile)
        self.historySizeEdit.setMinimum(1)
        self.historySizeEdit.setProperty("value", 50)
        self.historySizeEdit.setObjectName("historySizeEdit")
        self.gridLayout_3.addWidget(self.historySizeEdit, 0, 2, 1, 1)
        self.startupReloadEdit = QtWidgets.QCheckBox(self.tabFile)
        self.startupReloadEdit.setChecked(True)
        self.startupReloadEdit.setObjectName("startupReloadEdit")
        self.gridLayout_3.addWidget(self.startupReloadEdit, 1, 0, 1, 2)
        self.fileMonitoringEdit = QtWidgets.QCheckBox(self.tabFile)
        self.fileMonitoringEdit.setChecked(True)
        self.fileMonitoringEdit.setObjectName("fileMonitoringEdit")
        self.gridLayout_3.addWidget(self.fileMonitoringEdit, 2, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabFile)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.fileBackupEdit = QtWidgets.QRadioButton(self.groupBox_7)
        self.fileBackupEdit.setAutoExclusive(False)
        self.fileBackupEdit.setObjectName("fileBackupEdit")
        self.verticalLayout.addWidget(self.fileBackupEdit)
        self.codeBackupEdit = QtWidgets.QRadioButton(self.groupBox_7)
        self.codeBackupEdit.setAutoExclusive(False)
        self.codeBackupEdit.setObjectName("codeBackupEdit")
        self.verticalLayout.addWidget(self.codeBackupEdit)
        self.gridLayout_3.addWidget(self.groupBox_7, 3, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 4, 1, 1, 1)
        self.prefTab.addTab(self.tabFile, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pycodeDebugEdit = QtWidgets.QCheckBox(self.groupBox_6)
        self.pycodeDebugEdit.setObjectName("pycodeDebugEdit")
        self.horizontalLayout_4.addWidget(self.pycodeDebugEdit)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.gccPathEdit = QtWidgets.QLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gccPathEdit.sizePolicy().hasHeightForWidth())
        self.gccPathEdit.setSizePolicy(sizePolicy)
        self.gccPathEdit.setObjectName("gccPathEdit")
        self.horizontalLayout_5.addWidget(self.gccPathEdit)
        self.gccPathButton = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gccPathButton.sizePolicy().hasHeightForWidth())
        self.gccPathButton.setSizePolicy(sizePolicy)
        self.gccPathButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.gccPathButton.setObjectName("gccPathButton")
        self.horizontalLayout_5.addWidget(self.gccPathButton)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        spacerItem8 = QtWidgets.QSpacerItem(18, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.prefTab.addTab(self.tab, "")
        self.tabExecution = QtWidgets.QWidget()
        self.tabExecution.setObjectName("tabExecution")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabExecution)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabExecution)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.useThreadEdit = QtWidgets.QCheckBox(self.groupBox_3)
        self.useThreadEdit.setObjectName("useThreadEdit")
        self.horizontalLayout_2.addWidget(self.useThreadEdit)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.visuCheckBoxLayout = QtWidgets.QGroupBox(self.tabExecution)
        self.visuCheckBoxLayout.setObjectName("visuCheckBoxLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.visuCheckBoxLayout)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fitViewEdit = QtWidgets.QCheckBox(self.visuCheckBoxLayout)
        self.fitViewEdit.setChecked(True)
        self.fitViewEdit.setObjectName("fitViewEdit")
        self.verticalLayout_9.addWidget(self.fitViewEdit)
        self.integratedViewEdit = QtWidgets.QCheckBox(self.visuCheckBoxLayout)
        self.integratedViewEdit.setObjectName("integratedViewEdit")
        self.verticalLayout_9.addWidget(self.integratedViewEdit)
        self.visuInfoEdit = QtWidgets.QCheckBox(self.visuCheckBoxLayout)
        self.visuInfoEdit.setObjectName("visuInfoEdit")
        self.verticalLayout_9.addWidget(self.visuInfoEdit)
        self.verticalLayout_3.addWidget(self.visuCheckBoxLayout)
        self.textOutputBox = QtWidgets.QGroupBox(self.tabExecution)
        self.textOutputBox.setObjectName("textOutputBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.textOutputBox)
        self.verticalLayout_10.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.LPyConsoleButton = QtWidgets.QRadioButton(self.textOutputBox)
        self.LPyConsoleButton.setChecked(True)
        self.LPyConsoleButton.setAutoExclusive(False)
        self.LPyConsoleButton.setObjectName("LPyConsoleButton")
        self.verticalLayout_10.addWidget(self.LPyConsoleButton)
        self.systemConsoleButton = QtWidgets.QRadioButton(self.textOutputBox)
        self.systemConsoleButton.setChecked(False)
        self.systemConsoleButton.setAutoExclusive(False)
        self.systemConsoleButton.setObjectName("systemConsoleButton")
        self.verticalLayout_10.addWidget(self.systemConsoleButton)
        self.verticalLayout_3.addWidget(self.textOutputBox)
        spacerItem9 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.prefTab.addTab(self.tabExecution, "")
        self.profilingTab = QtWidgets.QWidget()
        self.profilingTab.setObjectName("profilingTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.profilingTab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.profilingTab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.profilingAnimatedButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.profilingAnimatedButton.setObjectName("profilingAnimatedButton")
        self.verticalLayout_7.addWidget(self.profilingAnimatedButton)
        self.profilingFinalPlotButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.profilingFinalPlotButton.setChecked(True)
        self.profilingFinalPlotButton.setObjectName("profilingFinalPlotButton")
        self.verticalLayout_7.addWidget(self.profilingFinalPlotButton)
        self.profilingNoPlotButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.profilingNoPlotButton.setObjectName("profilingNoPlotButton")
        self.verticalLayout_7.addWidget(self.profilingNoPlotButton)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.prefTab.addTab(self.profilingTab, "")
        self.verticalLayout_4.addWidget(self.prefTab)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(PreferenceDialog)
        self.prefTab.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PreferenceDialog.accept)
        self.buttonBox.rejected.connect(PreferenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferenceDialog)

    def retranslateUi(self, PreferenceDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferenceDialog.setWindowTitle(_translate("PreferenceDialog", "Preferences"))
        self.groupBox.setTitle(_translate("PreferenceDialog", "ToolBar"))
        self.label.setText(_translate("PreferenceDialog", "Show"))
        self.toolbarAppEdit.setItemText(0, _translate("PreferenceDialog", "Icons"))
        self.toolbarAppEdit.setItemText(1, _translate("PreferenceDialog", "Texts"))
        self.toolbarAppEdit.setItemText(2, _translate("PreferenceDialog", "Icons and texts"))
        self.toolbarAppEdit.setItemText(3, _translate("PreferenceDialog", "Texts below icons"))
        self.groupBox_2.setTitle(_translate("PreferenceDialog", "Text Editor"))
        self.label_2.setText(_translate("PreferenceDialog", "Font Family"))
        self.label_3.setText(_translate("PreferenceDialog", "Font Size"))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabAppearance), _translate("PreferenceDialog", "Appearance"))
        self.groupBox_4.setTitle(_translate("PreferenceDialog", "Tabulation"))
        self.spaceForTabEdit.setText(_translate("PreferenceDialog", "Replace by spaces"))
        self.label_4.setText(_translate("PreferenceDialog", "Tab size"))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabEditing), _translate("PreferenceDialog", "Editing"))
        self.label_5.setText(_translate("PreferenceDialog", "History max size"))
        self.startupReloadEdit.setText(_translate("PreferenceDialog", "Reload file at startup"))
        self.fileMonitoringEdit.setText(_translate("PreferenceDialog", "Check file change on disk."))
        self.groupBox_7.setTitle(_translate("PreferenceDialog", "Backup"))
        self.label_6.setText(_translate("PreferenceDialog", "Create backup file"))
        self.fileBackupEdit.setText(_translate("PreferenceDialog", "Of previous file before saving"))
        self.codeBackupEdit.setText(_translate("PreferenceDialog", "Of code before execution"))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabFile), _translate("PreferenceDialog", "File"))
        self.groupBox_6.setTitle(_translate("PreferenceDialog", "Parsing"))
        self.pycodeDebugEdit.setText(_translate("PreferenceDialog", "Show python code for debug."))
        self.groupBox_8.setTitle(_translate("PreferenceDialog", "Cython"))
        self.label_7.setText(_translate("PreferenceDialog", "GCC Path"))
        self.gccPathButton.setText(_translate("PreferenceDialog", "..."))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tab), _translate("PreferenceDialog", "Compilation"))
        self.groupBox_3.setTitle(_translate("PreferenceDialog", "Threading"))
        self.useThreadEdit.setText(_translate("PreferenceDialog", "Use thread (Experimental)."))
        self.visuCheckBoxLayout.setTitle(_translate("PreferenceDialog", "Visualization"))
        self.fitViewEdit.setText(_translate("PreferenceDialog", "Fit last view before animation."))
        self.integratedViewEdit.setText(_translate("PreferenceDialog", "Integrated viewer"))
        self.visuInfoEdit.setText(_translate("PreferenceDialog", "Display info at run"))
        self.textOutputBox.setTitle(_translate("PreferenceDialog", "Text Output"))
        self.LPyConsoleButton.setText(_translate("PreferenceDialog", "LPy Console"))
        self.systemConsoleButton.setText(_translate("PreferenceDialog", "System Console"))
        self.prefTab.setTabText(self.prefTab.indexOf(self.tabExecution), _translate("PreferenceDialog", "Execution"))
        self.groupBox_9.setTitle(_translate("PreferenceDialog", "Visualisation"))
        self.profilingAnimatedButton.setText(_translate("PreferenceDialog", "Animated Mode"))
        self.profilingFinalPlotButton.setText(_translate("PreferenceDialog", "Final plot"))
        self.profilingNoPlotButton.setText(_translate("PreferenceDialog", "No plot"))
        self.prefTab.setTabText(self.prefTab.indexOf(self.profilingTab), _translate("PreferenceDialog", "Profiling"))

