# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lsysmainwindow.ui'
#
# Created: Fri Jun 06 15:01:42 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563,589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0,21,563,549))
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtGui.QGridLayout(self.centralwidget)
        self.gridlayout.setObjectName("gridlayout")
        self.tabView = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabView.sizePolicy().hasHeightForWidth())
        self.tabView.setSizePolicy(sizePolicy)
        self.tabView.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabView.setObjectName("tabView")
        self.tab = QtGui.QWidget()
        self.tab.setGeometry(QtCore.QRect(0,0,438,458))
        self.tab.setObjectName("tab")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setObjectName("vboxlayout")
        self.codeeditor = LsysCodeEditor(self.tab)
        self.codeeditor.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.codeeditor.setFont(font)
        self.codeeditor.setTabStopWidth(20)
        self.codeeditor.setObjectName("codeeditor")
        self.vboxlayout.addWidget(self.codeeditor)
        self.frameFind = QtGui.QFrame(self.tab)
        self.frameFind.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFind.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFind.setObjectName("frameFind")
        self.gridlayout1 = QtGui.QGridLayout(self.frameFind)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(3)
        self.gridlayout1.setObjectName("gridlayout1")
        self.closeFind = QtGui.QToolButton(self.frameFind)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170,0,0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.ButtonText,brush)
        brush = QtGui.QBrush(QtGui.QColor(0,0,0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.ButtonText,brush)
        brush = QtGui.QBrush(QtGui.QColor(118,116,108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.ButtonText,brush)
        self.closeFind.setPalette(palette)
        self.closeFind.setObjectName("closeFind")
        self.gridlayout1.addWidget(self.closeFind,0,0,1,1)
        self.label_8 = QtGui.QLabel(self.frameFind)
        self.label_8.setObjectName("label_8")
        self.gridlayout1.addWidget(self.label_8,0,1,1,1)
        self.findEdit = QtGui.QLineEdit(self.frameFind)
        self.findEdit.setObjectName("findEdit")
        self.gridlayout1.addWidget(self.findEdit,0,2,1,1)
        self.findNextButton = QtGui.QPushButton(self.frameFind)
        self.findNextButton.setObjectName("findNextButton")
        self.gridlayout1.addWidget(self.findNextButton,0,3,1,1)
        self.findPreviousButton = QtGui.QPushButton(self.frameFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findPreviousButton.sizePolicy().hasHeightForWidth())
        self.findPreviousButton.setSizePolicy(sizePolicy)
        self.findPreviousButton.setObjectName("findPreviousButton")
        self.gridlayout1.addWidget(self.findPreviousButton,0,4,1,1)
        spacerItem = QtGui.QSpacerItem(61,23,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem,0,5,1,1)
        spacerItem1 = QtGui.QSpacerItem(161,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1,1,0,1,3)
        self.matchCaseButton = QtGui.QRadioButton(self.frameFind)
        self.matchCaseButton.setAutoExclusive(False)
        self.matchCaseButton.setObjectName("matchCaseButton")
        self.gridlayout1.addWidget(self.matchCaseButton,1,3,1,1)
        self.wholeWordButton = QtGui.QRadioButton(self.frameFind)
        self.wholeWordButton.setAutoExclusive(False)
        self.wholeWordButton.setObjectName("wholeWordButton")
        self.gridlayout1.addWidget(self.wholeWordButton,1,4,1,1)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2,1,5,1,1)
        self.vboxlayout.addWidget(self.frameFind)
        self.frameReplace = QtGui.QFrame(self.tab)
        self.frameReplace.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameReplace.setFrameShadow(QtGui.QFrame.Raised)
        self.frameReplace.setObjectName("frameReplace")
        self.hboxlayout = QtGui.QHBoxLayout(self.frameReplace)
        self.hboxlayout.setSpacing(3)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_9 = QtGui.QLabel(self.frameReplace)
        self.label_9.setObjectName("label_9")
        self.hboxlayout.addWidget(self.label_9)
        self.replaceEdit = QtGui.QLineEdit(self.frameReplace)
        self.replaceEdit.setObjectName("replaceEdit")
        self.hboxlayout.addWidget(self.replaceEdit)
        self.replaceButton = QtGui.QPushButton(self.frameReplace)
        self.replaceButton.setObjectName("replaceButton")
        self.hboxlayout.addWidget(self.replaceButton)
        self.replaceAllButton = QtGui.QPushButton(self.frameReplace)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.hboxlayout.addWidget(self.replaceAllButton)
        spacerItem3 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.vboxlayout.addWidget(self.frameReplace)
        self.tabView.addTab(self.tab,"")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setGeometry(QtCore.QRect(0,0,438,458))
        self.tab_5.setObjectName("tab_5")
        self.gridlayout2 = QtGui.QGridLayout(self.tab_5)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.gridlayout2.addWidget(self.label_3,0,0,1,1)
        self.authorsEdit = QtGui.QLineEdit(self.tab_5)
        self.authorsEdit.setObjectName("authorsEdit")
        self.gridlayout2.addWidget(self.authorsEdit,0,1,1,1)
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.gridlayout2.addWidget(self.label_4,1,0,1,1)
        self.intitutesEdit = QtGui.QLineEdit(self.tab_5)
        self.intitutesEdit.setObjectName("intitutesEdit")
        self.gridlayout2.addWidget(self.intitutesEdit,1,1,1,1)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setObjectName("label_5")
        self.gridlayout2.addWidget(self.label_5,2,0,1,1)
        self.copyrightEdit = QtGui.QLineEdit(self.tab_5)
        self.copyrightEdit.setObjectName("copyrightEdit")
        self.gridlayout2.addWidget(self.copyrightEdit,2,1,1,1)
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setObjectName("label_6")
        self.gridlayout2.addWidget(self.label_6,3,0,1,1)
        self.descriptionEdit = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setAcceptRichText(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridlayout2.addWidget(self.descriptionEdit,4,0,1,2)
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.gridlayout2.addWidget(self.label_7,5,0,1,1)
        self.referenceEdit = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceEdit.sizePolicy().hasHeightForWidth())
        self.referenceEdit.setSizePolicy(sizePolicy)
        self.referenceEdit.setMaximumSize(QtCore.QSize(16777215,80))
        self.referenceEdit.setAcceptRichText(False)
        self.referenceEdit.setObjectName("referenceEdit")
        self.gridlayout2.addWidget(self.referenceEdit,6,0,1,2)
        self.tabView.addTab(self.tab_5,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,438,458))
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.materialed = MaterialEditor(self.tab_2)
        self.materialed.setObjectName("materialed")
        self.hboxlayout1.addWidget(self.materialed)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.tabView.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,438,458))
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(9)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.hboxlayout2.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(1,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem4)
        self.animtimestep = QtGui.QSlider(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animtimestep.sizePolicy().hasHeightForWidth())
        self.animtimestep.setSizePolicy(sizePolicy)
        self.animtimestep.setMinimum(1)
        self.animtimestep.setMaximum(2000)
        self.animtimestep.setProperty("value",QtCore.QVariant(50))
        self.animtimestep.setOrientation(QtCore.Qt.Horizontal)
        self.animtimestep.setObjectName("animtimestep")
        self.hboxlayout2.addWidget(self.animtimestep)
        spacerItem5 = QtGui.QSpacerItem(10,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem5)
        self.animtimeSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.animtimeSpinBox.setDecimals(3)
        self.animtimeSpinBox.setSingleStep(0.1)
        self.animtimeSpinBox.setObjectName("animtimeSpinBox")
        self.hboxlayout2.addWidget(self.animtimeSpinBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.hboxlayout2.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parametersTable = QtGui.QTableView(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255,255,215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,QtGui.QPalette.AlternateBase,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,QtGui.QPalette.AlternateBase,brush)
        brush = QtGui.QBrush(QtGui.QColor(236,233,216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.Base,brush)
        brush = QtGui.QBrush(QtGui.QColor(255,255,175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,QtGui.QPalette.AlternateBase,brush)
        self.parametersTable.setPalette(palette)
        self.parametersTable.setAlternatingRowColors(True)
        self.parametersTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.parametersTable.setObjectName("parametersTable")
        self.verticalLayout.addWidget(self.parametersTable)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem6 = QtGui.QSpacerItem(20,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tabView.addTab(self.tab_3,"")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setGeometry(QtCore.QRect(0,0,438,458))
        self.tab_4.setObjectName("tab_4")
        self.gridlayout3 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout3.setObjectName("gridlayout3")
        self.helpDisplay = QtGui.QTextBrowser(self.tab_4)
        self.helpDisplay.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.helpDisplay.setAcceptRichText(True)
        self.helpDisplay.setObjectName("helpDisplay")
        self.gridlayout3.addWidget(self.helpDisplay,0,0,1,1)
        self.tabView.addTab(self.tab_4,"")
        self.gridlayout.addWidget(self.tabView,0,0,1,1)
        self.groupBox1 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName("groupBox1")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.groupBox1)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.runButton = QtGui.QPushButton(self.groupBox1)
        self.runButton.setObjectName("runButton")
        self.vboxlayout2.addWidget(self.runButton)
        self.animButton = QtGui.QPushButton(self.groupBox1)
        self.animButton.setObjectName("animButton")
        self.vboxlayout2.addWidget(self.animButton)
        self.stepButton = QtGui.QPushButton(self.groupBox1)
        self.stepButton.setObjectName("stepButton")
        self.vboxlayout2.addWidget(self.stepButton)
        self.rewindButton = QtGui.QPushButton(self.groupBox1)
        self.rewindButton.setObjectName("rewindButton")
        self.vboxlayout2.addWidget(self.rewindButton)
        self.clearButton = QtGui.QPushButton(self.groupBox1)
        self.clearButton.setObjectName("clearButton")
        self.vboxlayout2.addWidget(self.clearButton)
        spacerItem7 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem7)
        self.cancelButton = QtGui.QPushButton(self.groupBox1)
        self.cancelButton.setObjectName("cancelButton")
        self.vboxlayout2.addWidget(self.cancelButton)
        self.gridlayout.addWidget(self.groupBox1,0,1,1,1)
        self.interpreterDock = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreterDock.sizePolicy().hasHeightForWidth())
        self.interpreterDock.setSizePolicy(sizePolicy)
        self.interpreterDock.setFloating(False)
        self.interpreterDock.setObjectName("interpreterDock")
        self.dockWidgetContents = QtGui.QWidget(self.interpreterDock)
        self.dockWidgetContents.setGeometry(QtCore.QRect(0,22,545,18))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.interpreterDock.setWidget(self.dockWidgetContents)
        self.gridlayout.addWidget(self.interpreterDock,1,0,1,2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,563,21))
        self.menubar.setObjectName("menubar")
        self.menuL_systems = QtGui.QMenu(self.menubar)
        self.menuL_systems.setObjectName("menuL_systems")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecents = QtGui.QMenu(self.menuFile)
        self.menuRecents.setObjectName("menuRecents")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,570,563,19))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionAnimate = QtGui.QAction(MainWindow)
        self.actionAnimate.setObjectName("actionAnimate")
        self.actionStep = QtGui.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionRewind = QtGui.QAction(MainWindow)
        self.actionRewind.setObjectName("actionRewind")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionPythonShell = QtGui.QAction(MainWindow)
        self.actionPythonShell.setObjectName("actionPythonShell")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionUseThread = QtGui.QAction(MainWindow)
        self.actionUseThread.setCheckable(True)
        self.actionUseThread.setObjectName("actionUseThread")
        self.actionFitAnimationView = QtGui.QAction(MainWindow)
        self.actionFitAnimationView.setCheckable(True)
        self.actionFitAnimationView.setObjectName("actionFitAnimationView")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtGui.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutVPlants = QtGui.QAction(MainWindow)
        self.actionAboutVPlants.setObjectName("actionAboutVPlants")
        self.actionClearShell = QtGui.QAction(MainWindow)
        self.actionClearShell.setObjectName("actionClearShell")
        self.actionSyntax = QtGui.QAction(MainWindow)
        self.actionSyntax.setCheckable(True)
        self.actionSyntax.setObjectName("actionSyntax")
        self.actionComment = QtGui.QAction(MainWindow)
        self.actionComment.setObjectName("actionComment")
        self.actionUncomment = QtGui.QAction(MainWindow)
        self.actionUncomment.setObjectName("actionUncomment")
        self.actionInsertTab = QtGui.QAction(MainWindow)
        self.actionInsertTab.setObjectName("actionInsertTab")
        self.actionRemoveTab = QtGui.QAction(MainWindow)
        self.actionRemoveTab.setObjectName("actionRemoveTab")
        self.actionReplace = QtGui.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionParseDebug = QtGui.QAction(MainWindow)
        self.actionParseDebug.setCheckable(True)
        self.actionParseDebug.setObjectName("actionParseDebug")
        self.menuL_systems.addAction(self.actionRun)
        self.menuL_systems.addAction(self.actionAnimate)
        self.menuL_systems.addSeparator()
        self.menuL_systems.addAction(self.actionStep)
        self.menuL_systems.addAction(self.actionRewind)
        self.menuRecents.addAction(self.actionClear)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecents.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionComment)
        self.menuEdit.addAction(self.actionUncomment)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionInsertTab)
        self.menuEdit.addAction(self.actionRemoveTab)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSyntax)
        self.menuTools.addAction(self.actionUseThread)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionFitAnimationView)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionParseDebug)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuHelp.addAction(self.actionAboutVPlants)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuL_systems.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabView.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit,QtCore.SIGNAL("triggered()"),MainWindow.close)
        QtCore.QObject.connect(self.actionCopy,QtCore.SIGNAL("triggered()"),self.codeeditor.copy)
        QtCore.QObject.connect(self.actionCut,QtCore.SIGNAL("triggered()"),self.codeeditor.cut)
        QtCore.QObject.connect(self.actionPaste,QtCore.SIGNAL("triggered()"),self.codeeditor.paste)
        QtCore.QObject.connect(self.actionUndo,QtCore.SIGNAL("triggered()"),self.codeeditor.undo)
        QtCore.QObject.connect(self.codeeditor,QtCore.SIGNAL("undoAvailable(bool)"),self.actionUndo.setEnabled)
        QtCore.QObject.connect(self.actionRedo,QtCore.SIGNAL("triggered()"),self.codeeditor.redo)
        QtCore.QObject.connect(self.codeeditor,QtCore.SIGNAL("redoAvailable(bool)"),self.actionRedo.setEnabled)
        QtCore.QObject.connect(self.actionFind,QtCore.SIGNAL("triggered()"),self.frameFind.show)
        QtCore.QObject.connect(self.closeFind,QtCore.SIGNAL("pressed()"),self.frameFind.hide)
        QtCore.QObject.connect(self.actionSelect_All,QtCore.SIGNAL("triggered()"),self.codeeditor.selectAll)
        QtCore.QObject.connect(self.actionFind,QtCore.SIGNAL("triggered()"),self.findEdit.setFocus)
        QtCore.QObject.connect(self.actionFind,QtCore.SIGNAL("triggered()"),self.findEdit.selectAll)
        QtCore.QObject.connect(self.closeFind,QtCore.SIGNAL("pressed()"),self.frameReplace.hide)
        QtCore.QObject.connect(self.actionReplace,QtCore.SIGNAL("triggered()"),self.frameReplace.show)
        QtCore.QObject.connect(self.actionReplace,QtCore.SIGNAL("triggered()"),self.frameFind.show)
        QtCore.QObject.connect(self.actionFind,QtCore.SIGNAL("triggered()"),self.frameReplace.hide)
        QtCore.QObject.connect(self.actionReplace,QtCore.SIGNAL("triggered()"),self.findEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabView,self.codeeditor)
        MainWindow.setTabOrder(self.codeeditor,self.runButton)
        MainWindow.setTabOrder(self.runButton,self.animButton)
        MainWindow.setTabOrder(self.animButton,self.stepButton)
        MainWindow.setTabOrder(self.stepButton,self.rewindButton)
        MainWindow.setTabOrder(self.rewindButton,self.clearButton)
        MainWindow.setTabOrder(self.clearButton,self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton,self.closeFind)
        MainWindow.setTabOrder(self.closeFind,self.findEdit)
        MainWindow.setTabOrder(self.findEdit,self.replaceEdit)
        MainWindow.setTabOrder(self.replaceEdit,self.findNextButton)
        MainWindow.setTabOrder(self.findNextButton,self.findPreviousButton)
        MainWindow.setTabOrder(self.findPreviousButton,self.replaceButton)
        MainWindow.setTabOrder(self.replaceButton,self.replaceAllButton)
        MainWindow.setTabOrder(self.replaceAllButton,self.matchCaseButton)
        MainWindow.setTabOrder(self.matchCaseButton,self.wholeWordButton)
        MainWindow.setTabOrder(self.wholeWordButton,self.animtimeSpinBox)
        MainWindow.setTabOrder(self.animtimeSpinBox,self.helpDisplay)
        MainWindow.setTabOrder(self.helpDisplay,self.descriptionEdit)
        MainWindow.setTabOrder(self.descriptionEdit,self.copyrightEdit)
        MainWindow.setTabOrder(self.copyrightEdit,self.authorsEdit)
        MainWindow.setTabOrder(self.authorsEdit,self.intitutesEdit)
        MainWindow.setTabOrder(self.intitutesEdit,self.referenceEdit)
        MainWindow.setTabOrder(self.referenceEdit,self.animtimestep)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.closeFind.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.findNextButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.findPreviousButton.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.matchCaseButton.setText(QtGui.QApplication.translate("MainWindow", "Match Case", None, QtGui.QApplication.UnicodeUTF8))
        self.wholeWordButton.setText(QtGui.QApplication.translate("MainWindow", "Whole word", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceButton.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceAllButton.setText(QtGui.QApplication.translate("MainWindow", "Rep. All", None, QtGui.QApplication.UnicodeUTF8))
        self.tabView.setTabText(self.tabView.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Institutes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Copyright", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "References", None, QtGui.QApplication.UnicodeUTF8))
        self.tabView.setTabText(self.tabView.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabView.setTabText(self.tabView.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Time Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "s.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabView.setTabText(self.tabView.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabView.setTabText(self.tabView.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run!", None, QtGui.QApplication.UnicodeUTF8))
        self.animButton.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.stepButton.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.rewindButton.setText(QtGui.QApplication.translate("MainWindow", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.interpreterDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Python Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.menuL_systems.setTitle(QtGui.QApplication.translate("MainWindow", "L-systems", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecents.setTitle(QtGui.QApplication.translate("MainWindow", "Recents", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnimate.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStep.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRewind.setText(QtGui.QApplication.translate("MainWindow", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPythonShell.setText(QtGui.QApplication.translate("MainWindow", "Python Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUseThread.setText(QtGui.QApplication.translate("MainWindow", "Use Thread", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitAnimationView.setText(QtGui.QApplication.translate("MainWindow", "Fit Animate View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutVPlants.setText(QtGui.QApplication.translate("MainWindow", "About V. Plants", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearShell.setText(QtGui.QApplication.translate("MainWindow", "Clear Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSyntax.setText(QtGui.QApplication.translate("MainWindow", "Syntax Hightlight", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setText(QtGui.QApplication.translate("MainWindow", "Comment Block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUncomment.setText(QtGui.QApplication.translate("MainWindow", "Uncomment Block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertTab.setText(QtGui.QApplication.translate("MainWindow", "Insert Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveTab.setText(QtGui.QApplication.translate("MainWindow", "Remove Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParseDebug.setText(QtGui.QApplication.translate("MainWindow", "Parse Debug", None, QtGui.QApplication.UnicodeUTF8))

from lsyscodeeditor import LsysCodeEditor
from materialeditor import MaterialEditor
